const $=id=>document.getElementById(id), fmt=(x,d=1)=>Number(x).toFixed(d), money=x=>'$'+Math.round(Number(x)).toLocaleString();
let cases=[], selected=null, currentOptions=[];
const riskColor={critical:'#ff5b45',high:'#ff9b51',watch:'#d1b530',stable:'#46a58c'};
function switchView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`));document.querySelectorAll('.nav-link[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-link[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-view-target]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewTarget));$('descend').onclick=()=>switchView('decision');
function polar(cx,cy,r,a){const rad=(a-90)*Math.PI/180;return{x:cx+r*Math.cos(rad),y:cy+r*Math.sin(rad)}}
function renderOrbit(){const svg=$('fleet-orbit'),cx=535,cy=385,rings=[130,220,315];let html=rings.map((r,i)=>`<circle class="orbit-ring ${i===1?'dash':''}" cx="${cx}" cy="${cy}" r="${r}"/><text class="orbit-zone-label" x="${cx+r+8}" y="${cy+4}">${['IMMEDIATE','PLANNING','WATCH'][i]}</text>`).join('');const maxR=Math.max(...cases.map(x=>Number(x.predicted_rul)),1);cases.forEach((c,i)=>{const urgency=1-Math.min(Number(c.predicted_rul),maxR)/maxR;const r=300-urgency*165;const angle=(i/cases.length)*360+12;const p=polar(cx,cy,r,angle);const size=7+Math.min(1,Number(c.failure_risk||0))*9;html+=`<g class="asset-node ${c.risk_band} ${selected===c.asset_id?'selected':''}" data-id="${c.asset_id}" transform="translate(${p.x},${p.y})"><circle r="${size}"/><text x="${size+8}" y="4">${c.asset_label}</text></g>`});svg.innerHTML=html;svg.querySelectorAll('.asset-node').forEach(n=>n.onclick=()=>openCase(Number(n.dataset.id)))}
function renderFingerprint(points){const svg=$('fingerprint'),cx=260,cy=260;let html=[60,105,150,195].map(r=>`<circle class="finger-grid" cx="${cx}" cy="${cy}" r="${r}"/>`).join('');for(let i=0;i<24;i++){const p=polar(cx,cy,195,i*15);html+=`<line class="finger-grid" x1="${cx}" y1="${cy}" x2="${p.x}" y2="${p.y}"/>`}const pts=points.map((p,i)=>{const r=70+Number(p.health_index)*120;return polar(cx,cy,r,i*360/points.length)});html+=`<polygon class="finger-poly" points="${pts.map(p=>`${p.x},${p.y}`).join(' ')}"/>`;pts.forEach((p,i)=>{if(i%4===0)html+=`<circle class="finger-dot" cx="${p.x}" cy="${p.y}" r="4"/>`});svg.innerHTML=html}
function renderOptions(){const box=$('options');box.innerHTML=currentOptions.map((o,i)=>`<button class="route ${i===0?'selected':''}" data-index="${i}"><span>${o.id.replaceAll('_',' ')}</span><h3>${o.label}</h3><strong>${money(o.economics.expected_total_cost)}</strong><small>${o.timing} · risk input ${Math.round(o.risk_used*100)}%</small></button>`).join('');box.querySelectorAll('.route').forEach(b=>b.onclick=()=>selectOption(Number(b.dataset.index)));if(currentOptions.length)selectOption(0)}
function selectOption(i){document.querySelectorAll('.route').forEach((b,j)=>b.classList.toggle('selected',j===i));const o=currentOptions[i];$('option-detail').innerHTML=`<b>${o.label}</b> — ${o.interpretation} &nbsp; Modeled expected total cost: <b>${money(o.economics.expected_total_cost)}</b>.`}
async function openCase(id){selected=id;renderOrbit();const [d,o]=await Promise.all([fetch(`/api/assets/${id}/dossier`).then(r=>r.json()),fetch(`/api/assets/${id}/intervention-options`).then(r=>r.json())]);$('core-asset').textContent=d.asset_label;$('core-rul').textContent=`${fmt(d.predicted_rul)} cycles RUL`;$('core-risk').textContent=d.risk_band.toUpperCase();$('asset-title').textContent=d.asset_label;$('asset-sub').textContent=`cycle ${d.current_cycle} · ${d.recommended_action.replaceAll('_',' ')} · confidence ${Math.round(d.confidence*100)}%`;$('rul').textContent=fmt(d.predicted_rul);$('band').textContent=`90% band ${fmt(d.rul_interval[0])}–${fmt(d.rul_interval[1])}`;$('risk').textContent=`${Math.round(d.failure_risk*100)}%`;$('anomaly').textContent=fmt(d.anomaly_score,2);$('case-stamp').textContent=d.risk_band.toUpperCase();$('rationale').textContent=d.rationale;renderFingerprint(d.diagnostic_trace);currentOptions=o.options;renderOptions()}
function arcPath(cx,cy,r,a0,a1){const s=polar(cx,cy,r,a0),e=polar(cx,cy,r,a1),large=(a1-a0)>180?1:0;return`M ${s.x} ${s.y} A ${r} ${r} 0 ${large} 1 ${e.x} ${e.y}`}
function assignLanes(rows,cap){const laneEnds=Array(cap).fill(-Infinity);return rows.map(r=>{let lane=laneEnds.findIndex(e=>e<r.start_cycle);if(lane<0)lane=0;laneEnds[lane]=r.end_cycle;return{...r,lane}})}
function renderClock(p){const svg=$('schedule-clock'),cx=380,cy=380,base=300,cap=Math.max(1,Number($('bays').value));let html='';for(let lane=0;lane<cap;lane++)html+=`<circle class="clock-ring" cx="${cx}" cy="${cy}" r="${base-lane*38}"/>`;for(let c=1;c<=30;c++){const a=(c-1)*12,inner=base-cap*38-12,outer=base+15,s=polar(cx,cy,inner,a),e=polar(cx,cy,outer,a);html+=`<line class="clock-tick" x1="${s.x}" y1="${s.y}" x2="${e.x}" y2="${e.y}"/>`;if(c%5===0){const t=polar(cx,cy,base+34,a);html+=`<text class="clock-label" x="${t.x}" y="${t.y}" text-anchor="middle">${c}</text>`}}const rows=assignLanes([...p.commitments].sort((a,b)=>a.start_cycle-b.start_cycle),cap);rows.forEach(r=>{const rad=base-r.lane*38;const a0=(r.start_cycle-1)*12+2,a1=Math.max(a0+5,(r.end_cycle)*12-2);html+=`<path class="job-arc ${r.risk_band||'high'}" d="${arcPath(cx,cy,rad,a0,a1)}"><title>${r.asset_label} cycles ${r.start_cycle}-${r.end_cycle}</title></path>`});svg.innerHTML=html}
async function resolve(){const scenario=$('scenario').value,bays=$('bays').value;const p=await fetch(`/api/commitment-ledger?scenario=${scenario}&bay_capacity=${bays}&labor_hours_per_cycle=24`).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail||'plan error');return r.json()});const e=p.solver_evidence;$('solver-status').textContent=`${e.solver.replace('scipy_highs_milp','HiGHS MILP')} · ${e.status}`;$('solver-objective').textContent=money(e.objective_value);$('solver-gap').textContent=`MIP gap ${e.mip_gap??'n/a'}`;renderClock(p);$('commitments').innerHTML=p.commitments.map(x=>`<div class="commit-pill"><b>${x.asset_label}</b><span>C${x.start_cycle}–${x.end_cycle}</span></div>`).join('')}
async function init(){const [h,p,c]=await Promise.all([fetch('/api/health').then(r=>r.json()),fetch('/api/portfolio').then(r=>r.json()),fetch('/api/casebook?limit=18').then(r=>r.json())]);$('engine').textContent=h.status==='ok'?'ENGINE ONLINE':'ENGINE DEGRADED';$('dataset').textContent=(p.dataset||p.data_mode||'benchmark').replaceAll('_',' ');cases=c;selected=c[0]?.asset_id||null;renderOrbit();if(selected)await openCase(selected);await resolve()}
$('resolve').onclick=()=>resolve().catch(e=>{$('solver-status').textContent='PLAN ERROR';$('solver-objective').textContent=e.message});init().catch(e=>{$('engine').textContent='OBSERVATORY ERROR';console.error(e)});
